# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'

    - name: Build
      run: go build -v ./  && ls -la

    - name: Archive
      uses: actions/upload-artifact@v4.0.0
      with:
        name: apidemo
        path: ./apidemo
        
  image-build:
     runs-on: ubuntu-latest
     needs: go-build
     steps:
     - uses: actions/checkout@v3
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{ secrets.DOCKERAUSERNAME }}
        password: ${{ secrets.DOCKERPASSWD }}
     - name: Get artifacts
       uses: actions/download-artifact@master
       with:
         name: apidemo
         path: ./apidemo
     - name: Build & Publish to Registry
       run: |
         ls -la
         docker build . --file Dockerfile --tag registry.cn-guangzhou.aliyuncs.com/laikesi/apidemo:${{ github.sha }}
         docker images
         docker push registry.cn-guangzhou.aliyuncs.com/laikesi/apidemo:${{ github.sha }}


       
       
